apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: views-frontend
  namespace: argocd

spec:
  project: default

  source:
    repoURL: 'https://github.com/varunsoam007/views-frontend.git'
    targetRevision: main
    path: .

  destination:
    server: https://kubernetes.default.svc
    namespace: frontend

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
    - CreateNamespace=true