deployments:
  - name: views-frontend
    namespace: frontend
    replicas: 1

    containers:
      - name: views-frontend
        image:
          registry: docker.io
          repository: varunsoam/views-frontend
          tag: "343"

        ports:
          - name: http
            containerPort: 80

services:
  - name: views-frontend
    namespace: frontend
    type: LoadBalancer

    ports:
      - name: http
        port: 80
        targetPort: 80
        protocol: TCP