deployments:
  - name: views-frontend
    namespace: frontend-prod
    replicas: 3

    containers:
      - name: views-frontend-prod
        image:
          registry: docker.io
          repository: varunsoam/views-frontend
          tag: "343"

services:
  - name: views-frontend
    namespace: frontend-prod
    type: LoadBalancer

    ports:
      - name: http
        port: 80
        targetPort: 80