{{- define "global-templates.authorizationpolicy" -}}
{{- range .Values.authorizationpolicies }}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  {{- with .labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- toYaml .spec | nindent 2 }}
{{- end }}

{{- /* Auth auto-gen removed - use auth-templates-1.0.0 chart instead */ -}}
{{- end }}
