{{/*
Copyright (C) 2024 XM Cyber
Author: Devops Infra Team
*/}}

{{- define "global-templates.servicemonitor" -}}
{{- $global_values := .Values.global}}
{{- $common_defaults := .Values.common_defaults }}
{{- range .servicemonitors }}
{{- if not .disabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ required "ServiceMonitor has to include a name" .name }}
  namespace: {{ include "helpers.prefixNamespace" (dict "namespace" .namespace "global" $global_values) }}
  labels: {{ include "helpers.labels" (dict "context" $ "customLabels" .labels "defaultLabels" $common_defaults.labels) | nindent 4 }}
  {{- if or .annotations $common_defaults.annotations }}
  annotations: {{ include "helpers.annotations" (dict "context" $ "customAnnotations" .annotations "defaultAnnotations" $common_defaults.annotations) | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- if .selector }}
      {{- include "common.tplvalues.render" ( dict "value" .selector "context" $) | nindent 6 }}
      {{- else }}
      app.kubernetes.io/name: {{ .name }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
      {{- end }}
  {{- if .namespaceSelector }}
  namespaceSelector:
    {{- include "common.tplvalues.render" (dict "value" .namespaceSelector "context" $) | nindent 4 }}
  {{- end }}
  endpoints:
    {{- range .endpoints }}
    - port: {{ .port | default "http" }}
      {{- if .path }}
      path: {{ .path }}
      {{- end }}
      {{- if .interval }}
      interval: {{ .interval }}
      {{- end }}
      {{- if .scrapeTimeout }}
      scrapeTimeout: {{ .scrapeTimeout }}
      {{- end }}
      {{- if .scheme }}
      scheme: {{ .scheme }}
      {{- end }}
      {{- if .honorLabels }}
      honorLabels: {{ .honorLabels }}
      {{- end }}
      {{- if .relabelings }}
      relabelings:
        {{- include "common.tplvalues.render" (dict "value" .relabelings "context" $) | nindent 8 }}
      {{- end }}
      {{- if .metricRelabelings }}
      metricRelabelings:
        {{- include "common.tplvalues.render" (dict "value" .metricRelabelings "context" $) | nindent 8 }}
      {{- end }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
